import { Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['100' ,'200', '300', '400', '500', '600', '700', '800'], 
})

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto-condensed',
  weight: ['300', '400', '700'], 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
